[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Ultra-permissive CSP for OAuth testing
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src *; script-src * 'unsafe-eval' 'unsafe-inline'; style-src * 'unsafe-inline'; img-src * data: blob:; font-src * data:; connect-src *; media-src *; object-src *; child-src *; frame-src *; worker-src *; frame-ancestors *; form-action *; base-uri *;"

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 