[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Rewrite rule for Next.js app
[[redirects]]
  from = "/*"
  to = "/_next/static/:splat"
  status = 200
  force = false
  conditions = {path = ["/_next/static/*"]}

# Fallback rewrite rule
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200
  force = false 