[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 