[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Temporarily disable CSP to test OAuth
# [[headers]]
#   for = "/*"
#   [headers.values]
#     X-Frame-Options = "DENY"
#     X-Content-Type-Options = "nosniff"
#     Referrer-Policy = "strict-origin-when-cross-origin"

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 