[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# CSP Headers for OAuth compatibility
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://dapxfjkdfrcwxfqrdvga.supabase.co https://twitter.com https://x.com; connect-src 'self' https://dapxfjkdfrcwxfqrdvga.supabase.co https://api.twitter.com https://upload.twitter.com https://twitter.com https://x.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self' https://dapxfjkdfrcwxfqrdvga.supabase.co; frame-ancestors 'none'; frame-src https://twitter.com https://x.com https://dapxfjkdfrcwxfqrdvga.supabase.co;"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle all routes for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 